spring:
  datasource:
    url: jdbc:mysql://192.168.1.20:3306/test_db?useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: ${MySQL_USER}
    password: ${MySQL_PWD}
    driver-class-name: com.mysql.jdbc.Driver
    minimum-idle: 5
    maximum-pool-size: 20
    ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
    auto-commit: true
    ## 连接允许在池中闲置的最长时间，默认600000（10分钟），单位ms
    idle-timeout: 30000
    ## 连接池名称
    pool-name: LockHikari
    ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟，单位ms
    max-lifetime: 1800000
    ## 数据库连接超时时间,默认30秒，即30000，单位ms
    connection-timeout: 30000
    connection-test-query: SELECT 1
    initialization-mode: always
    schema: classpath:db/schema.sql