server:
  port: 8080

spring:
  mvc:
    favicon:
      enabled: false

#spring:
#  profiles:
#    active: test



# 模块分割线

---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: test